from PIL import Image

file = "Neutral_64.png"
out = "Export"

hald = Image.open(file)
image = hald.load()

lutSize = round((hald.width**2)**(1/3))

cube = open(out + "_" + str(lutSize) + ".cube", "w")
cube.write('#Generated by Serch\nTITLE "'+out+'"\n\n')
cube.write("#LUT Size\n")
cube.write("%s %d\n\n"%("LUT_3D_SIZE", lutSize))

for y in range(hald.height):
    for x in range(hald.width):
        r = round((image[x,y][0]/255), 6)
        g = round((image[x,y][1]/255), 6)
        b = round((image[x,y][2]/255), 6)
        cube.write('%08f %08f %08f\n' %(r, g, b))

cube.close()


        